"""your_migration_message

Revision ID: 2e1d8c310fcc
Revises: 
Create Date: 2026-08-21 10:32:21.965457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1d8c310fcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_phone'), 'owners', ['phone'], unique=True)
    op.create_table('shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_owner_id'), 'shops', ['owner_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('low_stock_threshold >= 0', name='ck_products_low_stock_threshold_non_negative'),
    sa.CheckConstraint('selling_price > 0', name='ck_products_selling_price_positive'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_products_stock_quantity_non_negative'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_shop_id', 'products', ['shop_id'], unique=False)
    op.create_index('ix_products_shop_id_is_active', 'products', ['shop_id', 'is_active'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('sold_by_type', sa.Enum('OWNER', 'WORKER', name='actortype'), nullable=False),
    sa.Column('sold_by_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'TELEBIRR', 'CBE_BIRR', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_created_at', 'sales', ['created_at'], unique=False)
    op.create_index('ix_sales_shop_id', 'sales', ['shop_id'], unique=False)
    op.create_index('ix_sales_shop_id_created_at', 'sales', ['shop_id', 'created_at'], unique=False)
    op.create_index('ix_sales_sold_by_id', 'sales', ['sold_by_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_shop_id', 'workers', ['shop_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('INITIAL', 'RESTOCK', 'SALE', 'ADJUSTMENT', 'RETURN', name='inventorymovementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_by_type', sa.Enum('OWNER', 'WORKER', name='actortype'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movements_created_at', 'inventory_movements', ['created_at'], unique=False)
    op.create_index('ix_inventory_movements_product_id', 'inventory_movements', ['product_id'], unique=False)
    op.create_index('ix_inventory_movements_shop_id', 'inventory_movements', ['shop_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_product_id', 'sale_items', ['product_id'], unique=False)
    op.create_index('ix_sale_items_sale_id', 'sale_items', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_items_sale_id', table_name='sale_items')
    op.drop_index('ix_sale_items_product_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_inventory_movements_shop_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_product_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_created_at', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_workers_shop_id', table_name='workers')
    op.drop_table('workers')
    op.drop_index('ix_sales_sold_by_id', table_name='sales')
    op.drop_index('ix_sales_shop_id_created_at', table_name='sales')
    op.drop_index('ix_sales_shop_id', table_name='sales')
    op.drop_index('ix_sales_created_at', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_products_shop_id_is_active', table_name='products')
    op.drop_index('ix_products_shop_id', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_shops_owner_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_owners_phone'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
